language: python
python:
   - "2.7"
before_install:
   # Move out of git directory to build root.
   - deactivate
   - cd ../..
   - pwd
install:
   # Download and extract the prebuilt binary.
   - wget -O nanshe-package.tgz https://www.dropbox.com/s/qhy2lhsk0ioge0p/nanshe-package.tgz?dl=0
   - tar -xzf nanshe-package.tgz
   - ls
   # Replace the src in the prebuilt binary with the one TravisCI cloned for us.
   - rm -rf nanshe-package.tgz
   - rm -rf nanshe-package/src/nanshe-git
   - mv $TRAVIS_REPO_SLUG nanshe-package/src/nanshe-git
   # Activate the environment.
   - cd nanshe-package
   - export BUILDEM_DIR=$(pwd)
   - echo "\$BUILDEM_DIR = ${BUILDEM_DIR}"
   - source $BUILDEM_DIR/bin/setenv_ilastik_gui.sh
   # Won't recognize setup.cfg unless we are in the source directory.
   - cd src/nanshe-git
script:
   # Run tests. Skip 3D tests as they take too long (~1hr).
   - python $BUILDEM_DIR/bin/nosetests -a '!3D'
   # Build documentation.
   - cd docs
   - make html
# Use container format for TravisCI to avoid termination due to insufficient resources.
sudo: false
