box: jakirkham/centos_drmaa_conda
build:
    steps:
        - script:
            name: Ensure clean repo.
            code: |-
                git update-index -q --refresh
                git submodule update --init --recursive

        - script:
            name: Configure and update conda.
            code: |-
                conda config --add channels conda-forge
                conda config --add channels nanshe
                conda config --set show_channel_urls True
                source activate root
                conda update -y --all
                conda clean -tipsy

        - script:
            name: Build and install the conda package.
            code: |-
                python setup.py bdist_conda
                conda create -y --use-local -n testenv nanshe==$(python setup.py --version)
                source activate testenv
                conda clean -tipsy

        - script:
            name: Install dependencies for cluster support.
            code: |-
                conda install -y drmaa
                conda clean -tipsy

        - script:
            name: Install dependencies for building docs.
            code: |-
                conda install -y sphinx
                conda install -y cloud_sptheme
                conda clean -tipsy

        - script:
            name: Install dependencies for profiling and monitoring coverage.
            code: |-
                conda install -y nose-timer
                conda install -y coverage
                conda install -y python-coveralls
                conda clean -tipsy

        - script:
            name: Test code.
            code: |-
                python setup.py nosetests --with-timer

        - script:
            name: Test documentation.
            code: |-
                python setup.py build_sphinx
